#!/usr/bin/env fish

function dude_help
    argparse '/header' -- $argv
    if set -q _flag_header
        echo "dude - declarative utilities for deployment of environment"
        echo ""
    end
    echo "subcommands:"
    echo "sync - sync configuration with current machine"
    echo ""
    echo "arguments:"
    echo "-h/--help: print this help text"
end

set dude_dir (status dirname)

argparse -s 'h/help' -- $argv
or dude_help

if test -z $argv[1]
    echo "Please supply a subcommand or a valid argument."
    dude_help --header
    return 1
end

switch $argv[1]
    case sync
        source "$dude_dir/sync.fish" $argv[2..]
    case '*'
        echo "Unknown subcommand $argv[1]"
        dude_help
        return 1
end
