wallpaper {
    monitor = desc:BNQ BenQ GL2250H T2E01026019
    path = ~/wallpapers/palebluedot_portrait.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/wallpapers/citizensleeper2.png
    fit_mode = cover
}

splash = false

