wallpaper {
    monitor = HDMI-A-1
    path = ~/wallpapers/palebluedot_portrait.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/wallpapers/citizensleeper2.png
    fit_mode = cover
}

splash = false

