
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule = tag +acryllic, match:class com.mitchellh.ghostty
windowrule = tag +acryllic2, match:class dev.zed.Zed
windowrule = tag +acryllic2, match:class ^(helium)$
windowrule = tag +ephemeral, match:title wiremix
windowrule = tag +ephemeral, match:title btop

windowrule = float on, match:class script-fu
windowrule = float on, match:class Tk

windowrule {
  name = acryllic
  match:tag = acryllic

  opacity = 0.97
}
windowrule {
  name = acryllic2
  match:tag = acryllic2

  opacity = 0.98
}
windowrule {
  name = ephemeral
  match:tag = ephemeral

  float = true
  center = on
  opacity = 1
  size = (monitor_w*0.45) (monitor_h*0.45)
}
