
# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# See https://wiki.hyprland.org/Configuring/Window-Rules/

windowrule = tag +acryllic, match:class com.mitchellh.ghostty
windowrule = tag +acryllic2, match:class dev.zed.Zed
# windowrule = tag +acryllic2, match:class ^(helium)$
windowrule = tag +ephemeral, match:title wiremix
windowrule = tag +ephemeral, match:title btop
windowrule = tag +ephemeral, match:class Bitwarden

windowrule = float on, match:class script-fu
windowrule = float on, match:class Tk

windowrule = no_initial_focus on, match:class PacketTracer
# windowrule = float on, match:class PacketTracer
# windowrule = no_anim on, match:class PacketTracer
# windowrule = no_blur on, match:class PacketTracer
# windowrule = no_dim on, match:class PacketTracer
# windowrule = no_shadow on, match:class PacketTracer
# windowrule = opaque on, match:class PacketTracer
# windowrule = immediate on, match:class PacketTracer
# windowrule = border_size 0, match:class PacketTracer
# windowrule = rounding 0, match:class PacketTracer
# windowrule = decorate 0, match:class PacketTracer
# windowrule = nearest_neighbor on, match:class PacketTracer
# windowrule = xray on, match:class PacketTracer
# windowrule = min_size 1 1, match:class PacketTracer
windowrule = keep_aspect_ratio on, match:class PacketTracer, match:title Cisco Packet Tracer
windowrule = focus_on_activate on, match:class PacketTracer, match:title Cisco Packet Tracer
windowrule = min_size 486 628, match:class PacketTracer, match:title Preference
windowrule = min_size 486 628, match:class PacketTracer, match:title .*outer.*
windowrule = min_size 772 700, match:class PacketTracer, match:title .*witch.*
windowrule = min_size 807 655, match:class PacketTracer, match:title .*PC.*
windowrule = min_size 791 648, match:class PacketTracer, match:title .*Save File.

windowrule {
  name = acryllic
  match:tag = acryllic

  opacity = 0.97
}
windowrule {
  name = acryllic2
  match:tag = acryllic2

  opacity = 0.98
}
windowrule {
  name = ephemeral
  match:tag = ephemeral

  float = true
  center = on
  opacity = 1
  size = (monitor_w*0.45) (monitor_h*0.45)
}
