set -g status-keys vi
set -g mode-keys   vi

setw -g mouse

set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 0
set -g history-limit 50000

set -g mouse on
set -g focus-events on

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

setw -g aggressive-resize on

bind -T root F12 set prefix None \; set key-table off
bind -T off F12 set -u prefix \; set -u key-table

